name: forrocwb.api

services:
  api:
    image: nandobfer/forrocwb.api
    container_name: forrocwb.api
    environment:
      - PORT=4105
      - DATABASE_URL=mysql://boz:Ewhblt69%21%40%23@boz.app.br:3306/forrocwb
      - URL=https://forrocwb.nandoburgos.dev
    ports:
      - "4105:4105"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  static_volume:
    name: "forrocwb_static_files"